{"name": "Проверка невозможности логина пользователя с некорректными данными", "status": "passed", "parameters": [{"name": "user_data", "value": "{'name': '', 'password': '12345', 'email': ''}"}], "start": 1726428904830, "stop": 1726428905137, "uuid": "09c12fb1-e4bd-4fb9-b942-f1f02c35e41b", "historyId": "ce8d1a862b6e35080c4700b72f833c12", "testCaseId": "8085b72d7bbb8e82aea363e1909f2273", "fullName": "tests.test_login_user.TestLoginUser#test_unable_login_user_with_incorrect_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "zurujal-osx"}, {"name": "thread", "value": "14231-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}